### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by cptX** [CamiAlfa/M365_DRV_STLINK#4]
On a Mi3 controller I'm trying to run the code both in linux and windows and I get the following errors:

~/codes/python/M365_DRV_STLINK-master $ ./flash_m365_1S.py

unsecuring device...
done
reading UUID
Traceback (most recent call last):
  File "./flash_m365_1S.py", line 58, in <module>
    UUID = oocd.read_memory(0x1FFFF7E8,3)
  File "/home/xxxxx/codes/python/M365_DRV_STLINK-master/openocd.py", line 120, in read_memory
    order = [int(raw[2 * i]) for i in range(len(raw) // 2)]
  File "/home/xxxxx/codes/python/M365_DRV_STLINK-master/openocd.py", line 120, in <listcomp>
    order = [int(raw[2 * i]) for i in range(len(raw) // 2)]
ValueError: invalid literal for int() with base 10: 'embedded:startup.tcl:449:'

Can anybody tell me what is wrong here?

In windows by using the m365rec.exe it works but using this code here either in linux or windows with python 3.8.10 throws the above error!

**Comment by ditrics** [comment]
Same here with m365 classic:

`C:\Users\anvert iroda\Downloads\M365_DRV_STLINK-master>python flash_m365_classic.py
unsecuring device...
done
reading UUID
done: 0673ff35 34315653 51184954
preparing sooter data...
flashing...
done
Traceback (most recent call last):
  File "flash_m365_classic.py", line 77, in <module>
    UUID2 = oocd.read_memory(0x0800F9B4,3)
  File "C:\Users\anvert iroda\Downloads\M365_DRV_STLINK-master\openocd.py", line 120, in read_memory
    order = [int(raw[2 * i]) for i in range(len(raw) // 2)]
  File "C:\Users\anvert iroda\Downloads\M365_DRV_STLINK-master\openocd.py", line 120, in <listcomp>
    order = [int(raw[2 * i]) for i in range(len(raw) // 2)]
ValueError: invalid literal for int() with base 10: 'embedded:startup.tcl:476:'`
